.TH KSTARS 1
.SH NAME
indiwebmanagerapp \- INDI Web Manager Configuration and management GUI
.SH SYNOPSIS
.B indiwebmanagerapp
.I [Qt-options] [KDE-options] [options]
.SH DESCRIPTION
.B INDIWebManagerApp
 is a program designed to support users of INDI, KStars, and other INDI Clients 
 by providing a GUI based interface to easily configure, launch, manage, and monitor an INDI Web Manager
 on either OS X or Linux.  This program will allow the usage of astronomical devices connected to this computer 
 by INDI Clients on this computer or any other computer on the local network through the launching and management
 of an INDI Web Manager.

.SH OPTIONS

.SH SEE ALSO
More detailed user documentation is available from https://github.com/rlancaste/INDIWebManagerApp
