/* Set INDI Library version */
#define INDI_VERSION_MAJOR   @CMAKE_INDI_VERSION_MAJOR@
#define INDI_VERSION_MINOR   @CMAKE_INDI_VERSION_MINOR@
#define INDI_VERSION_RELEASE @CMAKE_INDI_VERSION_RELEASE@
#define INDI_VERSION "@INDI_VERSION@"

/* Define INDI Data Dir */
#define DATA_INSTALL_DIR "@DATA_INSTALL_DIR@"
