FROM debian:latest

WORKDIR /tmp

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
    git \
    cmake build-essential zlib1g-dev \
    libcfitsio-dev libnova-dev libusb-1.0-0-dev libcurl4-gnutls-dev \
    libgsl-dev libjpeg-dev libfftw3-dev

RUN git clone https://github.com/google/googletest.git googletest && \
    cd googletest && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local . && \
    make && \
    make install && \
    rm -rf /tmp/googletest
