FROM centos:latest

WORKDIR /tmp

RUN yum -y install epel-release && yum -y upgrade && yum -y install \
    git \
    cmake gcc-c++ zlib-devel \
    cfitsio-devel libnova-devel libusb-devel libcurl-devel \
    gsl-devel libjpeg-devel fftw-devel

RUN git clone https://github.com/google/googletest.git googletest && \
    cd googletest && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local . && \
    make && \
    make install && \
    rm -rf /tmp/googletest
