#ifndef CONFIG_H
#define CONFIG_H

/* Define INDI Data Dir */
#cmakedefine INDI_DATA_DIR "@INDI_DATA_DIR@"

/* Define Driver version */
#define SHELYAK_USIS_VERSION_MAJOR @SHELYAK_USIS_VERSION_MAJOR@
#define SHELYAK_USIS_VERSION_MINOR @SHELYAK_USIS_VERSION_MINOR@

#endif // CONFIG_H
