name: Docker
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - '.github/docker/*'
      - '.github/workflows/docker.yml'
  schedule:
    - cron: '0 7 */7 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["debian", "debian-buster", "debian-i386", "ubuntu", "fedora"]

    steps:
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./.github/docker/Dockerfile.${{ matrix.container }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
