name: Linux

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["ubuntu", "debian", "debian-buster", "fedora"]

    container:
      image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}

    steps:
      - name: Get INDI Sources
        uses: actions/checkout@v3
        with:
          path: 'indi'

      - name: Build INDI Core
        run: |
          indi/scripts/indi-core-build.sh
          indi/scripts/indi-core-package-build.sh

      - name: Install INDI Core
        run: indi/scripts/indi-core-install.sh

      - name: Run INDI Core Test
        run: indi/scripts/indi-core-test.sh

      - name: Archive INDI Core Package
        uses: actions/upload-artifact@v2
        with:
          name: indi-core-package-${{ matrix.container }}
          path: packages/indi-core-package.tar
