name: Linux i386

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["debian-i386"]

    container:
      image: ghcr.io/indilib/${{ matrix.container }}

    steps:
      - name: Get INDI Sources
        uses: actions/checkout@v1 # Only v1 is compatible because of the different arch

      - name: Build INDI Core
        run: |
          scripts/indi-core-build.sh
          scripts/indi-core-package-build.sh

      - name: Install INDI Core
        run: scripts/indi-core-install.sh

      - name: Run INDI Core Test
        run: scripts/indi-core-test.sh
