name: MacOS

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  core:
    runs-on: macos-latest

    steps:
      - name: Get INDI Sources
        uses: actions/checkout@v4
        with:
          path: 'indi'

      - name: Install Pre-requisites
        run:  indi/scripts/requisites-install.sh

      - name: Build INDI Core
        run: |
          indi/scripts/indi-core-build.sh
          indi/scripts/indi-core-package-build.sh

      - name: Install INDI Core
        run: indi/scripts/indi-core-install.sh

      - name: Run INDI Core Test
        run: indi/scripts/indi-core-test.sh

      - name: Archive INDI Core Package
        uses: actions/upload-artifact@v4
        with:
          name: indi-core-package-macos
          path: packages/indi-core-package.tar

  homebrew:
    name: Homebrew formula
    runs-on: macos-latest

    steps:
      - name: Get INDI sources
        uses: actions/checkout@v4

      - name: Build and test formula
        run: |
          brew install --build-from-source ./Formula/indiserver.rb
          brew test indiserver

      - name: Audit formula
        run: |
          brew audit --new --strict --online Formula/indiserver.rb
          brew style Formula/indiserver.rb
