name: Package

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["ubuntu"]

    container:
      image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}

    steps:
      - name: Get INDI Sources
        uses: actions/checkout@v2
        with:
          path: 'indi'

      - name: Build INDI Core Package
        run: |
          indi/scripts/indi-core-deb.sh
